# Site settings
title:  Mônica Mota Ocariz
description: Blog sobre conhecimentos e aventuras do dia-a-dia
baseurl: ""
url: "https://monicamota.com.br/"

# User settings
username: Mônica Mota Ocariz
user_description: Programadora Junior
email: mota.ocariz@gmail.com
twitter_username: Monica_Ocariz
github_username:  monicamota
gplus_username: Monicamotaocariz #google+


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/ #define como será o link dos posts


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Sobre
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
