# Site settings
title:  Mocariz - Monica Mota
description: Blog sobre conhecimentos e aventuras do dia-a-dia
baseurl: ""
url: "https://mocariz.dev"

# User settings
username: Mônica Mota Ocariz
user_occupation: Desenvolvedora Front End
user_description:  Uma garota que gosta de viver histórias. Compartilho sobre aprendizados no universo front-end, livros, musicas, séries, experiencias e um pouco de chocolate.
email: mota.ocariz@gmail.com
twitter_username: mocariz_
github_username:  mocariz
instagran_username: mocariz


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/ #define como será o link dos posts


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'README.md',
  'gulpfile.js'
]
